.\" INPR
.TH pdf2laser 1 2015-01-18 GNU "NYC Resistor Tools"
.nh
.ad 1
.SH NAME
pdf2laser \- tool for printing PDF to an Epilog laser cutter over the network
.
.SH SYNOPSIS
.B pdf2laser
.RI [ OPTION "]... [" FILE ]
.
.SH DESCRIPTION
.B pdf2laser
converts PDF files to postscript files via
.B ghostscript
and then sends them to an Epilog laser cutter for \*(lqprinting\*(rq.
In addition to conversation
.B pdf2laser
will attempt to optimize the vector path of your cut.
While this optimization can be disabled (via
.BR \-O ", " \-\^\-no-optimize )
it will lead to locally faster cuts.
Laser cuts are composed of two components, the raster and the vector.
.PP
Raster is controlled by the options:
.IR DPI ", " MODE ", " SPEED ", " POWER ", and " SIZE "."
.PP
.I DPI
is the resolution of your print and is dictated by the
.I DPI
setting of the PDF file. The
.I SPEED
and
.I POWER
settings are just what is on the tin.
Values for the material you are cutting can be found on our wiki.
The
.I MODE
of your raster dictates how the image will be translated.
The three modes are mono, grey, and colour.
.PP
The mono raster mode uses a line or dot screen on any grey levels or colours.
This can be controlled with the
.I SIZE
parameter.
The default value of 8 makes a nice fine line screen on 600dpi engraving.
The grey raster mode maps the grey level to power level.
The power level is scaled to the raster power setting.
Unlike the windows driver which always 100% in this mode.
.PP
In colour mode, the primary and secondary colours are processed as separate
passes, using the grey level of the colour as a power level. The power level
is scaled to the raster power setting as in the grey mode. Note that red is
100% red, and non 100% green and blue, etc, so 50% red, 0% green/blue is not
counted as red, but counts as \*(lqgrey\*(rq. 100% red, and 50% green/blue
counts as red, half power. This means you can make distinct raster areas of
the page so that you do not waste time moving the head over blank space
between them.
.PP
Vector is controlled by the options:
.IR FREQUENCY ", " POWER ", and " SPEED "."
.PP
.I FREQUENCY
controls the duty cycle of the laser. It can be set from values between 10 and
5000. The higher the value, the more often the laser pulses each second and
how much energy is transferred to the material. A lower frequency, by merit of
transferring less heat to the material, will cause less charring and require a
higher power and lower speed to achieve the same depth of cut. Low frequencies
will produce perforation instead of a continuous cut in thinner materials like
paper.
.PP
The
.I POWER
and
.I SPEED
settings take between one and three numeric arguments, separated by
commas (e.g. 20,10). These correspond to the
.I POWER
and
.I SPEED
levels for the red, green, and blue values of the image. The colours are
defined in the same manner as in the colour mode of the raster section
above. The omitted values will be set to the value preceding it. If you set
only the red value then green and blue will use that, if you set red and green
then blue will use the green value.
.B DO NOT COUNT ON THIS FUNCTIONALITY, IT WILL CHANGE IN THE FUTURE\fR.
.
.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.
.SS GENERAL OPTIONS
.TP
.BR \-a ", " \-\^\-autofocus
Enable auto focus.
.TP
.BI \-n " JOBNAME" "\fR,\fP \-\^\-job=" JOBNAME
Set the display name of the job.
.TP
.BI \-p " ADDRESS" "\fR,\fP \-\^\-printer=" ADDRESS
IP address of the target printer.
.TP
.BI \-P " PRESET" "\fR,\fP \-\^\-preset=" PRESET
Select a default preset.
.SS RASTER OPTIONS
.TP
.BI \-d " DPI" "\fR,\fP \-\^\-dpi=" DPI
Resolution of raster artwork.
.TP
.BI \-m " MODE" "\fR,\fP \-\^\-mode=" MODE
Mode for rasterization (default mono).
.TP
.BI \-r " SPEED" "\fR,\fP \-\^\-raster-speed=" SPEED
Raster speed (0-100).
.TP
.BI \-R " POWER" "\fR,\fP \-\^\-raster-power=" POWER
Raster power (0-100).
.TP
.BI \-s " SIZE" "\fR,\fP \-\^\-screen-size=" SIZE
Photograph screen size (default 8).
.SS VECTOR OPTIONS
.TP
.BI \-f " FREQUENCY" "\fR,\fP \-\^\-frequency=" FREQUENCY
Vector frequency (10-5000).
.TP
.BR \-O ", " \-\^\-no-optimize
Disable vector optimization.
.TP
.BI \-V " POWER" "\fR,\fP \-\^\-vector-power=" POWER
Vector power for the R,G and B passes.
If only one power or speed is specified it will be used for all three.
.TP
.BI \-v " SPEED" "\fR,\fP \-\^\-vector-speed=" SPEED
Vector speed for the R,G and B passes.
If only one power or speed is specified it will be used for all three.
.SS GENERIC OPTIONS
.TP
.B \-\^\-help
Output a usage message and exit.
.TP
.B \-\^\-version
Output the version number of
.B pdf2laser
and exit.
.
.SH EXIT STATUS
In event of success
.B pdf2laser
will return 0 and exit. In event of an error
.B pdf2laser
will print a message to
.B stderr\fR,
return 1 and exit.
.
.SH EXAMPLES
When running
.B pdf2laser
you'll need to specify the
.I ADDRESS
of the laser cutter you are printing to. It is the only mandatory argument.
Most of the other flags have default values but you will want to specify
.I POWER
for both raster and vector as the defaults do not really help very much.
Most of the time when you use
.B pdf2laser
the command call will look like so.
.RS
.TP
.B pdf2laser "\fR\E\\\fP"
.br
.BI "\-\^\-printer " ADDRESS
\E\
.br
.BI "\-\^\-dpi " DPI
\E\
.br
.BI "\-\^\-raster-power " POWER
\E\
.br
.BI "\-\^\-raster-speed " SPEED
\E\
.br
.BI "\-\^\-frequency " FREQUENCY
\E\
.br
.BI "\-\^\-vector-power " POWER
\E\
.br
.BI "\-\^\-vector-speed " SPEED
\E\
.br
.B FILE
.RE
.PP
You can consult our wiki for the values to replace those fields with for the
material you are cutting.
.PP
When cutting and rastering 1/8th inch birch plywood the call would look as such.
.RS
.TP
.B pdf2laser "\fR\E\\\fP"
.br
.BI "\-\^\-printer " 192.168.1.4
\E\
.br
.BI "\-\^\-dpi " 300
\E\
.br
.BI "\-\^\-raster-power " 40
\E\
.br
.BI "\-\^\-raster-speed " 100
\E\
.br
.BI "\-\^\-frequency " 5
\E\
.br
.BI "\-\^\-vector-power " 100
\E\
.br
.BI "\-\^\-vector-speed " 12
\E\
.br
.B awesome_design.pdf
.RE
.
.SH NOTES
Currently if you are at the NYC Resistor space you do not need to specify an
.I ADDRESS
for the laser cutter as it is hard coded.
.B DO NOT COUNT ON THIS FUNCTIONALITY, IT WILL CHANGE IN THE FUTURE\fR.
In general, I have attempted to translate the previous program verbatim except
where change has been necessary for legal and direct functionality
reasons. The 0.x.x line of
.B pdf2laser
will continue in this vein and when I can I'll backport new functionality to
it. That being said, I have big plans (time permitting) for this tool and that
will involve some fairly large breaking changes to the interface of the
program.
.
.SH BUGS
Bug reports and issues may be posted on
https://github.com/zellio/pdf2laser/issues
.
.\" .SH CREDITS
.\" .
.SH THANKS
Thanks goes to Andrew and Arnold LTD and Brandon Edens for the
.B cups-epilog
driver on which this code is based.
Further thanks goes to Trammel Hudson for converting the
.B cups-epilog
driver into a command line tool. Finally special thanks goes to NYC Resistor
for providing a laser cutter to work with and for being a community that
fosters this kind of work.
.
.SH AUTHORS
.PP
The authors of the original
.B cups-epilog
driver are Andrews & Arnold LTD. <info@aaisp.net.uk> and AS220 Labs <brandon@as220.org>.
.PP
.B pdf2laser
was converted to a command line tool by Trammell Hudson <hudson@osresearch.net>.
.PP
The current maintainer is Zachary Elliott <contact@zell.io>.
.
.\" .SH SEE ALSO
.\" .
