.\" INPR
.TH pdf2laser 1 2015-08-01 GNU "NYC Resistor Tools"
.SH NAME
pdf2laser \- a tool to send PDF files to an Epilog laser cutter over wifi
.SH SYNOPSIS
pdf2laser [OPTION...] FILE
.SH DESCRIPTION
.PP
It's a program
.SH OPTIONS
.PP
Mandatory arguments to long options are mandatory for short options too.
.SS GENERAL OPTIONS
.IP "\fB\-p, \-\^\-printer ip\fP"
ip-address of the target printer
.IP "\fB\-P, \-\-preset name\fP"
Select a default preset
.IP "\fB\-a, \-\-autofocus\fP"
Enable auto focus
.IP "\fB\-n, \-\-job Jobname\fP"
Set the job name to display
.SS RASTER OPTIONS
.IP "\fB\-d, \-\-dpi DPI\fP"
Resolution of raster artwork
.IP "\fB\-R, \-\-raster-power 0-100\fP"
Raster power
.IP "\fB\-r, \-\-raster-speed 0-100\fP"
Raster speed
.IP "\fB\-m, \-\-mode mono|grey|color\fP"
Mode for rasterization (default mono)
.IP "\fB\-s, \-\-screen-size N\fP"
Photograph screen size (default 8)
.SS VECTOR OPTIONS
.IP "\fB\-f, \-\-frequency 10-5000\fP"
Vector frequency
.IP "\fB\-O, \-\-no-optimize\fP"
Disable vector optimization
.IP "\fB\-V, \-\-vector-power 0-100[,G,B]\fP"
Vector power for the R,G and B passes
.IP "\fB\-v, \-\-vector-speed 0-100[,G,B]\fP"
Vector speed. If only one power or speed is specified it will be used for all three
.SS GENERIC OPTIONS
.IP "\fB\-h, \-\-help\fP"
print a short help message and exit.
.IP "\fB\-\-version\fP"
print the pdf2laser version number and exit.
.SH EXIT STATUS
.SH NOTES
.SH BUGS
.SH EXAMPLE
.SH CREDITS
.SH THANKS
.SH AUTHORS
.SH SEE ALSO
